steps:
- name: gcr.io/k8s-minikube/prow-test:v0.0.1
  entrypoint: 'bash'
  args:
    - -c
    - |
      git clone https://github.com/kubernetes/minikube
      cd minikube
      make
      ./out/minikube start --force-systemd --force
      kubectl get pods -A
options:
  machineType: N1_HIGHCPU_8